### PR TITLE
Added lots of questions; cleaned up comments.

### PR DESCRIPTION
**Pull request by jchodera**

### CODE REVIEW

**Comment by jchodera** [comment]
Hm. Not sure why this can't be merged.

**Comment by jchodera** [comment]
Maybe you can just grab this one file?

**Comment by jchodera** [comment]
Oh!  Because you added comments after I started working.  Sorry!

**Comment by pgrinaway** [comment]
No worries. I'll answer these questions and comments tonight + reconcile the changes. Thanks for the comments!

**Pull request merged**
